### ISSUE TITLE
libeSPDI and UVC header streams bug (Linux)

### ISSUE THREAD

**Issue by sh0** [slightech/MYNT-EYE-D-SDK#13]
Since Linux kernel version 4.16-rc1 there have been some changes to `uvcvideo` driver which seem to break libeSPDI. This [commit](https://github.com/torvalds/linux/commit/088ead25524583e2200aa99111bea2f66a86545a#diff-890fa74a20ebb7e5a65cdccc9c4c284d) adds UVC video header streams as separate `/dev/videoX` nodes for each UVC device. It means that previously MYNT EYE D device mapping looked like this:
* `/dev/video0` - color stream
* `/dev/video1` - depth stream

Now, from kernel 4.16+, it looks like this:
* `/dev/video0` - color stream
* `/dev/video1` - UVC headers for color stream
* `/dev/video2` - depth stream
* `/dev/video3` - UVC headers for depth stream

This confuses libeSPDI which can only find color stream and no depth stream.

Would it be possible for you to submit this bug to Etron? Eventually new kernels will become available on Ubuntu and other platforms so it becomes necessary to deal with this sooner or later.

**Comment by wdxybhb** [comment]
Hello, I have the same issue with "Cannot read depth data #24"
I have checked my Linux kernel which is Linux 4.4, so is it possible that my kernel version causes this problem? Or, can I fix this issue by promoting my kernel from 4.4 to 4.14?
Many thanks!

**Comment by harjeb** [comment]
Thanks for reporting it, we‘ll report this bug to Etron sooner. @wdxybhb you could install 4.15 kernal to avoid this issue temporarily.

**Comment by sh0** [comment]
I have a temporary fix for this bug. For `libeSPDI.so.3.0.24.05` change byte at address `0x023842` from `0x01` to `0x02`. On the command line this can be done as follows

    printf '\x02' | dd of=libeSPDI.so.3.0.24.05 bs=1 seek=145474 count=1 conv=notrunc

Note that with this patch the library will likely no longer work with kernel versions lower than 4.16.

**Comment by wdxybhb** [comment]
> I have a temporary fix for this bug. For `libeSPDI.so.3.0.24.05` change byte at address `0x023842` from `0x01` to `0x02`. On the command line this can be done as follows
> 
> ```
> printf '\x02' | dd of=libeSPDI.so.3.0.24.05 bs=1 seek=145474 count=1 conv=notrunc
> ```
> 
> Note that with this patch the library will likely no longer work with kernel versions lower than 4.16.

Sorry for interrupting. Would you please tell how to make change on the aarch64 .so files? Because I am currently using the arm-based embedded board for the camera. Thanks so much!!

**Comment by sh0** [comment]
@wdxybhb For `aarch64` binary `libeSPDI.so.3.0.24.05` try changing byte at address `0x025ba9` from `0x04` to `0x08`. I have no way of testing if it works, but I'm pretty sure it is correct.

I'm actually not sure if you have this bug. The kernel 4.4 shouldn't have this issue unless the `uvcvideo` changes were backported (which I think is unlikely). From experience of using ARM boards I can tell that they have lots of USB issues, especially with USB 3.0. In many cases the USB driver fails if you transfer too much data concurrently. So the color stream alone might work, but if you open both streams you might get an error.

**Comment by wdxybhb** [comment]
Thank you so much. You are so professional! Actually, I have solved this problem this morning just like you mentioned.
Currently I have two different arm boards with same Debian and kernel version (uname-r), one could work and the other does not. I think the board with problem may have modified kernel because I downloaded the kernel form its company. And yes, opening two 1280 streams may fail by chance. So I changed the resolution to 640*480. And it works currently.
Thanks again mate!




| |
张桃源
邮箱：wdxybhb@126.com
|

签名由 网易邮箱大师 定制

On 04/30/2019 18:28, Siim Meerits wrote:

@wdxybhb For aarch64 binary libeSPDI.so.3.0.24.05 try changing byte at address 0x025ba9 from 0x04 to 0x08. I have no way of testing if it works, but I'm pretty sure it is correct.

I'm actually not sure if you have this bug. The kernel 4.4 shouldn't have this issue unless the uvcvideo changes were backported (which I think is unlikely). From experience of using ARM boards I can tell that they have lots of USB issues, especially with USB 3.0. In many cases the USB driver fails if you transfer too much data concurrently. So the color stream alone might work, but if you open both streams you might get an error.

**Comment by jingshaojing** [comment]
> > I have a temporary fix for this bug. For `libeSPDI.so.3.0.24.05` change byte at address `0x023842` from `0x01` to `0x02`. On the command line this can be done as follows
> > ```
> > printf '\x02' | dd of=libeSPDI.so.3.0.24.05 bs=1 seek=145474 count=1 conv=notrunc
> > ```
> > 
> > 
> > Note that with this patch the library will likely no longer work with kernel versions lower than 4.16.
> 
> Sorry for interrupting. Would you please tell how to make change on the aarch64 .so files? Because I am currently using the arm-based embedded board for the camera. Thanks so much!!
 I have the same question on Ubuntu 18.03, which kernel version is5.3.0,and I have done as you said ,but  
the problem is still.Is there another solution?thanks

**Comment by jingshaojing** [comment]
> I have a temporary fix for this bug. For `amd64` binary `libeSPDI.so.3.0.24.05` change byte at address `0x023842` from `0x01` to `0x02`. On the command line this can be done as follows
> 
> ```
> printf '\x02' | dd of=libeSPDI.so.3.0.24.05 bs=1 seek=145474 count=1 conv=notrunc
> ```
> 
> Note that with this patch the library will likely no longer work with kernel versions lower than 4.16.

I have the same question on Ubuntu 18.04.4, which kernel version is5.3.0,and I have done as you said ,but
the problem is still.Is there another solution?thanks

**Comment by IshitaTakeshi** [comment]
I followed the instructions [here](https://github.com/KumarRobotics/flea3#optimizing-usb-performance-under-linux)

In `/etc/default/grub`, rewriting 

```GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"```

to 

```GRUB_CMDLINE_LINUX_DEFAULT="quiet splash usbcore.usbfs_memory_mb=1024"```

and running `sudo update-grub` solved the problem temporarily. 

The environment is Xubuntu 20.04 kernel 5.4.0-64-generic. 

However the problem occurred again in the next morning...

**Comment by IshitaTakeshi** [comment]
Sorry for complaining here, but we all purchased a $300 device and have faced the same problem, then we came here.  
But there's no software support and the only reliable way to solve the problem is to downgrade the kernel to 4.15 which is already 3 years old.  
The problem occurs in the proprietary library so we cannot solve them by ourselves.  
I just want to say "please".

**Comment by project-pantheon** [comment]
> Sorry for complaining here, but we all purchased a $300 device and have faced the same problem, then we came here.
> But there's no software support and the only reliable way to solve the problem is to downgrade the kernel to 4.15 which is already 3 years old.
> The problem occurs in the proprietary library so we cannot solve them by ourselves.
> I just want to say "please".

I am yet another customer who found himself stuck in the same situation which I think it is quite absurd. Has there been any update from this situation? I cannot use that kernel because the laptop is too new and nothing works.... and even the workaround no longer works given the fact that now the library is also libeSPDI.so.3.1.4.1 and no longer the one for which there was the workaround....

I find unbelievable that they keep selling these cameras being aware that basically they do not work on recent hw/kernels...and just do not care about solving this issue...

If anybody has a new workaround for this new version libeSPDI.so.3.1.4.1 please share it with us...

**Comment by sh0** [comment]
@IshitaTakeshi @project-pantheon 

I haven't used MYNT devices for quite a while, but tried one today with the `libeSPDI.so.3.1.4.1` library. It seems to work with kernel 5.11.11 (Gentoo) x86_64. Device is found correctly and I can start streaming as well. I didn't look at the depth data, but color seems to work.

I also looked at what the driver is doing internally:

- First `uname` is used to check kernel version. If it is 4.16 or newer then `version = 2` else `version = 1`. This variable is used later.
- Driver starts scanning for `/dev/video%d` devices starting from `index = 0` up to `index < 6`. If it finds a MYNT device with correct properties it proceeds to next step.
- Driver searches for secondary stream by first setting `index += version`. It searches for second stream again up to `index < 6`.

Can you post what `/dev/video` nodes you have on your system? If you have multiple USB camera devices so that there are more than 6 `/dev/video` nodes then you may run into problems.

Also what kernel version are you running? It would also be useful to see the console log. `EtronDI_Init` function should be called with second parameter set `true` to get more logging info. A good log with color and depth streams found at `/dev/video0` and `/dev/video2` looks like this:

```
EtronDI_Init
I/eSPDI_API: eSPDI: EtronDI_InitunameData.release = 5.11.11-gentoo
version 5.11.11
CVideoDevice: /dev/video0
m_Adi.device_list[0] = /dev/video0
CVideoDevice: /dev/video2
GetV4l2BusInfo +
GetV4l2BusInfo -
m_Adi.device_list2[0] = /dev/video2
CVideoDevice: /dev/video1
CVideoDevice: /dev/video2
CVideoDevice: /dev/video3
CVideoDevice: /dev/video4
CVideoDevice: /dev/video5
CVideoDevice: /dev/video0
CVideoDevice: /dev/video2
```

Recent industry practice is to open-source core camera access libraries (e.g. Intel RealSense, Microsoft Azure Kinect etc.). Unfortunately Etron Tech looks too old-school to do something like this. I mean they are still using Flash on their website 😂 I will look into developing an open-source alternative, but I'm not sure I can sink that much time into something that I'm not getting paid for.

**Comment by project-pantheon** [comment]
@sh0 

Thanks for your reply. Actually, your clear explanation made me think about a quick workaround, that ended up working just fine :-) 

Let me explain, our laptop (lenovo X1 Extreme Gen 3) has an integrated camera, so looking at the devices we had something like 

/dev/video0 -> Integrated Camera 
/dev/video1 -> Integrated Camera
/dev/video2 -> Integrated Camera
/dev/video3 -> Integrated Camera

/dev/video4 -> Mynt Eye
/dev/video5 -> Mynt Eye
/dev/video6 -> Mynt Eye
/dev/video7 -> Mynt Eye


Since you were mentioning that going above 6 may cause problems I thought about disabling the integrated webcam from the BIOS, and this made the trick :-)

Do you think is there anyway to fix this issue without disabling the integrated camera?

As far as the system we are using is concerned, it is an Ubuntu 18.04 LTS with kernel 5.4.0-72, as detailed in the following

Linux  5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Best,

**Comment by sh0** [comment]
@project-pantheon Good to know this trick worked!

You should be able to change the maximum device search range from 6 to 128 by applying the following patch to `amd64` version of `libeSPDI.so.3.1.4.1`:

* Change byte at address `0x011672` from `0x05` to `0x79`
* Change byte at address `0x011940` from `0x05` to `0x79`

Using the `dd` tool this patch works out as follows:

* `printf '\x79' | dd of=libeSPDI.so.3.1.4.1 bs=1 seek=71282 count=1 conv=notrunc`
* `printf '\x79' | dd of=libeSPDI.so.3.1.4.1 bs=1 seek=72000 count=1 conv=notrunc`

I didn't have time to test this patch, but it should work. Let me know if there is any interest for ARM library patch as well.

@harjeb Maybe you can report this bug to Etron?

**Comment by project-pantheon** [comment]
@sh0 

I am glad to confirm that your solution worked perfectly!!! I can tell you more... :-) We have two MYNT-EYE and now I was able to have both of them working at the same time after having also re-enabled the integrated camera. That is,  I have 12 videoX dev files, more specifically:

/dev/video0 -> Integrated Camera
/dev/video1 -> Integrated Camera
/dev/video2 -> Integrated Camera
/dev/video3 -> Integrated Camera

/dev/video4 -> Mynt Eye1
/dev/video5 -> Mynt Eye1
/dev/video6 -> Mynt Eye1
/dev/video7 -> Mynt Eye1


/dev/video8 -> Mynt Eye2
/dev/video9 -> Mynt Eye2
/dev/video10 -> Mynt Eye2
/dev/video11 -> Mynt Eye2

and everything just worked beautifully, meaning the first 4 video dev files were properly skipped and the other  8 video dev files were properly recognized and associated (4 each) to each of the two cameras.

Now MYNT-EYE devices can be be properly used in Ubuntu 18.04 and Ubuntu 20.04 :-)

Thanks a lot!

P.S.: I have also wrote an email to Etron yesterday to let them know about this issue.
